### ISSUE TITLE
wiki linux steps

### ISSUE THREAD

**Issue by JulioOrdonezV** [janunezc/pvcloud#32]
It would be nice to add some steps on how to configure a Linux server/environment the main difference would be that you need to install node using this:

`curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -`

`sudo apt-get install -y nodejs`

you might need to create a symlink to the nodejs binary

`ln -s /usr/bin/nodejs /usr/bin/node`

This is for Debian based distributions, there are instructions for other distributions as well

https://github.com/nodesource/distributions

**Comment by janunezc** [comment]
I added your instructions to our WIKI page.

https://github.com/janunezc/pvcloud/wiki/Development-Environment-Setup
